FROM rocker/ml-verse

RUN install2.r --error \
    languageserver \
    httpgd \
    svglite \
    tidymodels \
    bigrquery \
    DBI \
    glue \
    lme4 \
    stacks \
    randomForest \
    xgboost \
    vip \
    styler \
    finetune \
    gt \
    gtsummary

RUN installGithub.r \
    ropensci/targets \
    awconway/eicu_nitro
