FROM rocker/ml-verse

RUN install2.r --error \
    tidymodels \
    embed \
    bigrquery \
    DBI \
    glue \
    stacks \
    randomForest \
    xgboost

RUN installGithub.r \
    ropensci/targets 
