FROM rocker/ml-verse

RUN install2.r --error \
    tidymodels \
    embed \
    bigrquery \
    DBI \
    glue \
    stacks \
    randomForest \
    xgboost \
    vip \
    styler \
    finetune \
    gt \
    gtsummary

RUN installGithub.r \
    ropensci/targets 
